baseURL = "https://chatat.org/"
languageCode = "en-us"
title = "ChatAt"
theme = ["PaperMod"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[languages]
  [languages.en]
    contentDir = "content/english"
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "ChatAt"
    [languages.en.params.homeInfoParams]
      Title = "Welcome to ChatAt!"
      Content = "Your lightweight, accessible platform for sharing written content."
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "books"
      name = "Books"
      url = "/books/"
      weight = 20
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 30

  [languages.ar]
    contentDir = "content/arabic"
    languageName = "العربية"
    languageCode = "ar-sa"
    weight = 2
    title = "شات آت"
    rtl = true
    [languages.ar.params.homeInfoParams]
      Title = "مرحباً بكم في شات آت!"
      Content = "منصتكم الخفيفة والمتاحة لمشاركة المحتوى المكتوب."
    [[languages.ar.menu.main]]
      identifier = "about"
      name = "حول"
      url = "/about/"
      weight = 10
    [[languages.ar.menu.main]]
      identifier = "books"
      name = "الكتب"
      url = "/books/"
      weight = 20
    [[languages.ar.menu.main]]
      identifier = "contact"
      name = "تواصل معنا"
      url = "/contact/"
      weight = 30

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRss = true
  disableScrollToTop = false
  hideFooter = true
  ShowLastmod = true
  ShowToc = true
  TocOpen = true

[params.assets]
  customCSS = ["css/custom.css"]

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

