[build]
  command = "hugo --minify --disableKinds=RSS"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_ENV = "production"
