backend:
  name: github # Or gitlab, bitbucket depending on your Git provider
  branch: master # Your main branch
  repo: Emadshenouda-hash/ChatAt.org
  auth_type: pkce
  auth_scope: "repo"
  client_id: uCe8wg51HnOASqsmgrWtTXUSPpljmP6A
  base_url: https://dev-az01750y0vdro7u5.us.auth0.com
   

media_folder: "static/images/uploads"   # Where images will be stored in the repo
public_folder: "/images/uploads"        # How the images will be accessed publicly

collections:
  - name: "pages"
    label: "Pages (English)"
    folder: "content/english"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages_ar"
    label: "Pages (Arabic)"
    folder: "content/arabic"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
